# Generated by Django 2.0.2 on 2018-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_menuitemmaster_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemmaster',
            name='item',
            field=models.CharField(choices=[(1, 'INFO'), (2, 'WORK'), (3, 'OTHER')], default=1, max_length=10),
        ),
    ]
