# Generated by Django 2.0.2 on 2018-04-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_menuitemmaster_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitemmaster',
            old_name='item',
            new_name='item_type',
        ),
    ]
