# Generated by Django 2.0.2 on 2018-04-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180406_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemmaster',
            name='thumbnail',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
