# Generated by Django 2.0.2 on 2018-06-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_menuitemmaster_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='place',
        ),
        migrations.AlterField(
            model_name='menuitemmaster',
            name='item_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
