# Generated by Django 2.0.2 on 2018-06-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20180612_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemmaster',
            options={'verbose_name': '付箋', 'verbose_name_plural': '付箋s'},
        ),
        migrations.AddField(
            model_name='menuitemmaster',
            name='order_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
