# Generated by Django 2.0.2 on 2018-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20180612_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmaster',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menuitemmaster',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='menuitemmaster',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
