# Generated by Django 2.0.2 on 2018-06-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20180612_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmaster',
            name='attributes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemmaster',
            name='order_number',
            field=models.IntegerField(),
        ),
    ]
