# Generated by Django 2.0.2 on 2018-06-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20180612_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmaster',
            name='attributes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitemmaster',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
