# Generated by Django 2.0.2 on 2018-09-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20180612_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=10)),
                ('attributes', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('order_number', models.IntegerField()),
            ],
            options={
                'verbose_name': '付箋(大分類)',
                'verbose_name_plural': '付箋(大分類)s',
                'ordering': ['order_number'],
            },
        ),
        migrations.RenameModel(
            old_name='MenuItemMaster',
            new_name='MenuItem',
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order_number'], 'verbose_name': '付箋(小分類)', 'verbose_name_plural': '付箋(小分類)s'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.CharField(max_length=10),
        ),
    ]
