# Generated by Django 2.0.2 on 2018-10-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20180929_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url_sub',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
