# Generated by Django 2.0.2 on 2018-10-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_menuitem_url_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('possword', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='manager',
            name='person',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='person',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
