# Generated by Django 2.0.2 on 2018-10-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20181016_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='possword',
            new_name='password',
        ),
    ]
